version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    build: .
    container_name: identity_provider_app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-service-account.json
      - AUTH_MODE=firebase
      - USE_FIREBASE=true
      - DB_HOST=postgres
      - DB_USER=auth
      - DB_PASS=auth123
      - DB_NAME=auth_db
      - JWT_SECRET=your_jwt_secret_key_change_in_production
    volumes:
      - .:/usr/src/app
      - ./secrets/firebase-service-account.json:/run/secrets/firebase-service-account.json:ro
    command: npm start
