version: "3.8"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/base.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: identity_provider_app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/fir-authentification-978a0-firebase-adminsdk-fbsvc-9049c47239.json
      - USE_FIREBASE=true
      - DB_HOST=postgres
      - DB_USER=auth
      - DB_PASS=auth123
      - DB_NAME=auth_db
    volumes:
      - .:/usr/src/app
      - ./secrets/fir-authentification-978a0-firebase-adminsdk-fbsvc-9049c47239.json:/run/secrets/fir-authentification-978a0-firebase-adminsdk-fbsvc-9049c47239.json:ro
    command: npm start
